/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsCouponIdRouteImport } from './routes/events.$couponId'
import { Route as MyCouponsRouteImport } from './routes/my.coupons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCouponIdRoute = EventsCouponIdRouteImport.update({
  id: '/events/$couponId',
  path: '/events/$couponId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCouponsRoute = MyCouponsRouteImport.update({
  id: '/my/coupons',
  path: '/my/coupons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$couponId': typeof EventsCouponIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$couponId': typeof EventsCouponIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$couponId': typeof EventsCouponIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/events/$couponId'
    | '/my/coupons'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/signup' | '/events/$couponId' | '/my/coupons' | '/events'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/events/$couponId'
    | '/my/coupons'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventsCouponIdRoute: typeof EventsCouponIdRoute
  MyCouponsRoute: typeof MyCouponsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$couponId': {
      id: '/events/$couponId'
      path: '/events/$couponId'
      fullPath: '/events/$couponId'
      preLoaderRoute: typeof EventsCouponIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/coupons': {
      id: '/my/coupons'
      path: '/my/coupons'
      fullPath: '/my/coupons'
      preLoaderRoute: typeof MyCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsCouponIdRoute: EventsCouponIdRoute,
  MyCouponsRoute: MyCouponsRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
