/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalysisRouteImport } from './routes/admin.analysis'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsCouponRoundIdRouteImport } from './routes/events.$couponRoundId'
import { Route as MyCouponsRouteImport } from './routes/my.coupons'
import { Route as AdminCampaignsIndexRouteImport } from './routes/admin.campaigns.index'
import { Route as AdminCampaignsCouponRoundIdRouteImport } from './routes/admin.campaigns.$couponRoundId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalysisRoute = AdminAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCouponRoundIdRoute = EventsCouponRoundIdRouteImport.update({
  id: '/events/$couponRoundId',
  path: '/events/$couponRoundId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCouponsRoute = MyCouponsRouteImport.update({
  id: '/my/coupons',
  path: '/my/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsIndexRoute = AdminCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsCouponRoundIdRoute =
  AdminCampaignsCouponRoundIdRouteImport.update({
    id: '/campaigns/$couponRoundId',
    path: '/campaigns/$couponRoundId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/system': typeof AdminSystemRoute
  '/events/$couponRoundId': typeof EventsCouponRoundIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/campaigns/$couponRoundId': typeof AdminCampaignsCouponRoundIdRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/system': typeof AdminSystemRoute
  '/events/$couponRoundId': typeof EventsCouponRoundIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/campaigns/$couponRoundId': typeof AdminCampaignsCouponRoundIdRoute
  '/admin/campaigns': typeof AdminCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/system': typeof AdminSystemRoute
  '/events/$couponRoundId': typeof EventsCouponRoundIdRoute
  '/my/coupons': typeof MyCouponsRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/campaigns/$couponRoundId': typeof AdminCampaignsCouponRoundIdRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/admin/analysis'
    | '/admin/system'
    | '/events/$couponRoundId'
    | '/my/coupons'
    | '/admin/'
    | '/events/'
    | '/admin/campaigns/$couponRoundId'
    | '/admin/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/analysis'
    | '/admin/system'
    | '/events/$couponRoundId'
    | '/my/coupons'
    | '/admin'
    | '/events'
    | '/admin/campaigns/$couponRoundId'
    | '/admin/campaigns'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/admin/analysis'
    | '/admin/system'
    | '/events/$couponRoundId'
    | '/my/coupons'
    | '/admin/'
    | '/events/'
    | '/admin/campaigns/$couponRoundId'
    | '/admin/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventsCouponRoundIdRoute: typeof EventsCouponRoundIdRoute
  MyCouponsRoute: typeof MyCouponsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analysis': {
      id: '/admin/analysis'
      path: '/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AdminAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$couponRoundId': {
      id: '/events/$couponRoundId'
      path: '/events/$couponRoundId'
      fullPath: '/events/$couponRoundId'
      preLoaderRoute: typeof EventsCouponRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/coupons': {
      id: '/my/coupons'
      path: '/my/coupons'
      fullPath: '/my/coupons'
      preLoaderRoute: typeof MyCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns/': {
      id: '/admin/campaigns/'
      path: '/campaigns'
      fullPath: '/admin/campaigns/'
      preLoaderRoute: typeof AdminCampaignsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns/$couponRoundId': {
      id: '/admin/campaigns/$couponRoundId'
      path: '/campaigns/$couponRoundId'
      fullPath: '/admin/campaigns/$couponRoundId'
      preLoaderRoute: typeof AdminCampaignsCouponRoundIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalysisRoute: typeof AdminAnalysisRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampaignsCouponRoundIdRoute: typeof AdminCampaignsCouponRoundIdRoute
  AdminCampaignsIndexRoute: typeof AdminCampaignsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalysisRoute: AdminAnalysisRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCampaignsCouponRoundIdRoute: AdminCampaignsCouponRoundIdRoute,
  AdminCampaignsIndexRoute: AdminCampaignsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsCouponRoundIdRoute: EventsCouponRoundIdRoute,
  MyCouponsRoute: MyCouponsRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
